spring:
  application:
    name: conte
  datasource:
    url: jdbc:postgresql://localhost:5432/conte
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8081

http-url:
  product-service: http://localhost:8080
